-- Seed products (matching existing hardcoded data)
INSERT INTO products (id, name, description, long_description, price, currency, category, artisan, country, image, tags, in_stock) VALUES
('hand-thrown-clay-bowl', 'Hand-Thrown Clay Bowl', 'Traditional terracotta bowl with hand-painted geometric patterns inspired by Roma motifs.', 'This beautiful hand-thrown clay bowl is crafted using techniques passed down through generations of Roma potters in central Serbia. Each piece is individually shaped on a traditional wheel, dried slowly in open air, and fired in a wood-burning kiln. The geometric patterns are hand-painted using natural pigments, making every bowl truly one-of-a-kind.', 45.00, 'EUR', 'Pottery & Ceramics', 'Dragan M.', 'Serbia', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=600&fit=crop', ARRAY['handmade','pottery','traditional'], true),
('woven-kilim-runner', 'Woven Kilim Runner', 'Handwoven wool kilim with traditional Balkans diamond pattern in natural dyes.', 'This stunning kilim runner is handwoven on a traditional loom by skilled textile artisans in Kosovo. Made from locally sourced wool and colored with natural plant-based dyes, it features the iconic diamond pattern found throughout Balkans weaving traditions. Each runner takes approximately two weeks to complete.', 120.00, 'EUR', 'Textiles & Weaving', 'Fatima H.', 'Kosovo', 'https://images.unsplash.com/photo-1600166898405-da9535204843?w=600&h=600&fit=crop', ARRAY['handwoven','textile','wool'], true),
('filigree-silver-pendant', 'Filigree Silver Pendant', 'Delicate sterling silver filigree pendant with traditional Roma swirl design.', 'This exquisite pendant showcases the ancient art of silver filigree, a technique perfected by Roma silversmiths over centuries.', 85.00, 'EUR', 'Jewelry & Metalwork', 'Elena V.', 'North Macedonia', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop', ARRAY['silver','filigree','jewelry'], true),
('carved-walnut-cutting-board', 'Carved Walnut Cutting Board', 'Hand-carved serving board from Bosnian walnut with decorative border pattern.', 'Crafted from a single piece of aged Bosnian walnut, this serving and cutting board features a delicately carved border inspired by traditional Roma woodcarving motifs.', 55.00, 'EUR', 'Woodwork & Carving', 'Alen K.', 'Bosnia', 'https://images.unsplash.com/photo-1588165171080-c89acfa5ee83?w=600&h=600&fit=crop', ARRAY['wood','walnut','kitchen'], true),
('embroidered-linen-tablecloth', 'Embroidered Linen Tablecloth', 'Hand-embroidered linen tablecloth with traditional floral patterns in red and gold.', 'This luxurious tablecloth is crafted from natural linen and adorned with hand-embroidered floral patterns.', 95.00, 'EUR', 'Textiles & Weaving', 'Mira S.', 'Albania', 'https://images.unsplash.com/photo-1594040226829-7f251ab46d80?w=600&h=600&fit=crop', ARRAY['embroidery','linen','tablecloth'], true),
('copper-coffee-pot-cezve', 'Copper Coffee Pot (Cezve)', 'Hand-hammered copper cezve for traditional Balkans coffee with brass handle.', 'This hand-hammered copper cezve is an essential piece of Balkans coffee culture.', 40.00, 'EUR', 'Jewelry & Metalwork', 'Marko D.', 'Montenegro', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=600&fit=crop', ARRAY['copper','coffee','handmade'], true),
('leather-satchel-bag', 'Leather Satchel Bag', 'Vegetable-tanned leather satchel with hand-stitched details and brass buckle.', 'This timeless satchel is made from vegetable-tanned cowhide leather.', 150.00, 'EUR', 'Leather Goods', 'Besnik Q.', 'Albania', 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop', ARRAY['leather','bag','handstitched'], true),
('ajvar-homemade-spread', 'Homemade Ajvar Spread', 'Traditional roasted red pepper and eggplant spread made from a family recipe.', 'This rich, smoky ajvar is made from hand-roasted red peppers and eggplant.', 12.00, 'EUR', 'Food & Spices', 'Jovana P.', 'Serbia', 'https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?w=600&h=600&fit=crop', ARRAY['food','ajvar','traditional'], true),
('ceramic-espresso-set', 'Ceramic Espresso Cup Set', 'Set of 4 hand-glazed ceramic espresso cups with saucers in earthy tones.', 'This set of four espresso cups with matching saucers is hand-thrown and glazed.', 60.00, 'EUR', 'Pottery & Ceramics', 'Samir T.', 'North Macedonia', 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&h=600&fit=crop', ARRAY['ceramic','espresso','set'], true),
('hand-carved-wooden-flute', 'Hand-Carved Wooden Flute', 'Traditional kaval flute carved from plum wood with decorative burnt patterns.', 'This traditional kaval flute is hand-carved from aged plum wood.', 35.00, 'EUR', 'Woodwork & Carving', 'Ismet B.', 'Kosovo', 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&h=600&fit=crop', ARRAY['music','flute','woodcarving'], true),
('balkans-spice-collection', 'Balkans Spice Collection', 'Curated set of 6 traditional Balkans spice blends in handmade ceramic jars.', 'This collection brings together six signature spice blends used across the Western Balkans.', 48.00, 'EUR', 'Food & Spices', 'Amina R.', 'Bosnia', 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=600&fit=crop', ARRAY['spices','collection','ceramic'], true),
('leather-journal-embossed', 'Embossed Leather Journal', 'Hand-bound journal with embossed Roma sun motif and recycled cotton pages.', 'This elegant journal features a cover of vegetable-tanned leather embossed with a traditional Roma sun motif.', 38.00, 'EUR', 'Leather Goods', 'Liridon G.', 'Kosovo', 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop', ARRAY['leather','journal','handbound'], true)
ON CONFLICT (id) DO NOTHING;

-- Seed services (matching existing hardcoded data)
INSERT INTO services (id, name, title, description, long_description, category, hourly_rate, fixed_rate_from, currency, rating, review_count, location, country, image, badges, available, response_time, completed_jobs) VALUES
('dragan-plumber-belgrade', 'Dragan P.', 'Licensed Plumber', 'Experienced plumber specializing in residential repairs.', 'With over 15 years of experience, Dragan provides reliable plumbing services across greater Belgrade.', 'Home Repair', 25, 30, 'EUR', 4.9, 87, 'Belgrade', 'Serbia', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=400&fit=crop&crop=face', ARRAY['Verified','Top Rated'], true, 'Under 1 hour', 312),
('fatima-dogsitter-pristina', 'Fatima K.', 'Professional Pet Sitter', 'Loving pet care including dog walking and house sitting.', 'Fatima has been caring for pets professionally for 5 years.', 'Pet Care', 10, 15, 'EUR', 5.0, 63, 'Pristina', 'Kosovo', 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=400&fit=crop', ARRAY['Verified','Top Rated'], true, 'Under 30 min', 198),
('alen-electrician-sarajevo', 'Alen M.', 'Certified Electrician', 'Certified electrician offering residential and commercial electrical work.', 'Alen is a fully certified electrician with 12 years of experience.', 'Home Repair', 30, 40, 'EUR', 4.8, 52, 'Sarajevo', 'Bosnia', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400&h=400&fit=crop&crop=face', ARRAY['Verified','Certified'], true, 'Under 2 hours', 245),
('mira-cleaning-tirana', 'Mira B.', 'Professional House Cleaner', 'Thorough, reliable house cleaning and deep cleaning services.', 'Mira runs a small cleaning team providing residential cleaning services across Tirana.', 'Cleaning', 12, 25, 'EUR', 4.9, 94, 'Tirana', 'Albania', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=400&fit=crop', ARRAY['Verified','Eco-Friendly'], true, 'Under 1 hour', 410),
('stefan-handyman-skopje', 'Stefan N.', 'General Handyman', 'Jack-of-all-trades handyman for furniture assembly and repairs.', 'Stefan handles a wide range of home improvement tasks.', 'Home Repair', 18, 20, 'EUR', 4.7, 41, 'Skopje', 'North Macedonia', 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=400&fit=crop&crop=face', ARRAY['Verified'], true, 'Under 3 hours', 156),
('elena-tutor-belgrade', 'Elena R.', 'Language & Music Tutor', 'Native Serbian speaker offering language tutoring.', 'Elena is a qualified language teacher offering one-on-one and small group lessons.', 'Tutoring & Lessons', 15, NULL, 'EUR', 5.0, 38, 'Belgrade', 'Serbia', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face', ARRAY['Verified','Top Rated'], true, 'Under 2 hours', 89),
('besnik-moving-tirana', 'Besnik L.', 'Moving & Delivery Service', 'Reliable moving and delivery service with a van.', 'Besnik and his team provide professional moving services across Tirana.', 'Transport & Moving', 20, 35, 'EUR', 4.6, 29, 'Tirana', 'Albania', 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&h=400&fit=crop&crop=face', ARRAY['Verified'], true, 'Under 3 hours', 178),
('jovana-hairdresser-podgorica', 'Jovana S.', 'Mobile Hairdresser & Stylist', 'Professional hairdresser offering cuts, coloring, and styling.', 'Jovana brings the salon to you with 8 years of experience.', 'Beauty & Wellness', 15, 12, 'EUR', 4.9, 56, 'Podgorica', 'Montenegro', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=400&fit=crop', ARRAY['Verified','Top Rated'], true, 'Under 1 hour', 267),
('marko-it-belgrade', 'Marko V.', 'Computer & Phone Repair', 'Fast, affordable computer and smartphone repairs.', 'Marko is a skilled IT technician offering tech support.', 'IT & Digital', 20, 15, 'EUR', 4.8, 44, 'Belgrade', 'Serbia', 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=400&h=400&fit=crop', ARRAY['Verified'], true, 'Under 2 hours', 203),
('amina-catering-sarajevo', 'Amina H.', 'Traditional Balkans Catering', 'Authentic home-cooked Balkans catering for events.', 'Amina provides catering services featuring traditional Bosnian and Roma cuisine.', 'Events & Catering', 0, 80, 'EUR', 5.0, 31, 'Sarajevo', 'Bosnia', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=400&fit=crop', ARRAY['Verified','Top Rated'], true, 'Under 3 hours', 95),
('liridon-dogwalker-pristina', 'Liridon G.', 'Dog Walker & Pet Trainer', 'Energetic dog walker and basic obedience trainer.', 'Liridon is passionate about dogs and offers daily walking services.', 'Pet Care', 8, 10, 'EUR', 4.7, 22, 'Pristina', 'Kosovo', 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop', ARRAY['Verified'], true, 'Under 1 hour', 134),
('ana-tailor-skopje', 'Ana T.', 'Seamstress & Tailor', 'Skilled seamstress offering clothing alterations.', 'Ana has been sewing for over 20 years.', 'Beauty & Wellness', 12, 8, 'EUR', 4.9, 47, 'Skopje', 'North Macedonia', 'https://images.unsplash.com/photo-1556740758-90de940a6755?w=400&h=400&fit=crop', ARRAY['Verified','Top Rated'], true, 'Under 2 hours', 189)
ON CONFLICT (id) DO NOTHING;

-- Seed admin users (SHA-256 hashes)
-- petrica@redi-ngo.eu / Ppapadie83*
-- richard@redi-ngo.eu / Welcome2REDI*
INSERT INTO admin_users (email, password_hash, role, name) VALUES
('petrica@redi-ngo.eu', '7b9c026b943c1db21293ca14ae723c32c2249e3170869a039ffdc4901e43f6b7', 'superadmin', 'Petrica'),
('richard@redi-ngo.eu', '06e97d38201662749b98fae635b26fb07c1cfc023705fa97c809ac8a665c6ea7', 'admin', 'Richard')
ON CONFLICT (email) DO NOTHING;
